# run: conda env create --file environment.yml
# to update run: conda env update --file environment.yml

name: FDTrees
channels:
  - defaults
dependencies:
  - python>=3.8
  - numpy=1.20.3
  - matplotlib=3.3.4
  - pandas=1.2.4
  - scikit-learn=1.2.0
  - nbformat=5.1.3
  - tqdm=4.59.0
  - ipywidgets=7.6.3
  - ipykernel=5.3.4
  - xlrd
  - pip=21.0.1
  - pip:
    - pytest
    - wandb
    - numba==0.54.0
    - shap
    - simple-parsing==0.0.15.post1